name: Bug Report
description: Create a report to help us improve. Clearly attach screenshots or video to help reproduce the issue quickly. Include a sample file if the problem involves image formats.
labels: ['\U0001F41E bug']
body:
  - type: markdown
    attributes:
      value: |
        ❗ **Before you fill in this bug report template**
        Please search open/closed issues and discussions before submitting. The bug might be already known and fixed before.

  - type: input
    id: os-version
    attributes:
      label: Windows OS version
      placeholder: e.g. Windows 11 24H2
    validations:
      required: true
- type: input
    id: ig-version
    attributes:
      label: ImageGlass version
      placeholder: e.g. 9.3.1.518
      description: |
        - ✅ Do provide full version number found in ImageGlass About dialog (press F1)
        - ❌ Don't use "latest"
    validations:
      required: true
- type: input
    id: ig-release
    attributes:
      label: ImageGlass release
      placeholder: e.g. Classic or Store
      description: Use "Store" if you installed ImageGlass from MS Store.
    validations:
      required: true

- type: textarea
    id: reproduction-steps
    attributes:
      label: 1️⃣ Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll down to...
        4. See error when...
    validations:
      required: true
  
  - type: textarea
    id: actual-behavior
    attributes:
      label: 2️⃣ Actual behavior
      description: Use list bullets to make it clear and concise.
    validations:
      required: true

- type: textarea
    id: expected-behavior
    attributes:
      label: 3️⃣ Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

- type: textarea
    id: media
    attributes:
      label: 4️⃣ Screenshots / Video / Sample image file
      description: |
        - ✅ Do attach SCREENSHOTS, VIDEO to help explain your problem quickly.
        - ✅ Do attach a SAMPLE FILE if the problem involves image formats.
    validations:
      required: true
      
  - type: textarea
    id: additional-context
    attributes:
      label: 5️⃣ Additional context
      description: Add any other context about the problem here.
